export const BRAND = {
  id: 'baazex',
  name: 'Baazex Academy',
  shortName: 'Baazex',
  engineName: 'Baazex Engine',
  company: 'Baazex Financial Services L.L.C',
  url: 'https://www.baazex.com',
  host: 'baazex.com',
  storagePrefix: 'baazex.academy',
  demoStudentEmail: 'student@baazex.com',
  demoAdminEmail: 'admin@baazex.com',
  colors: {
    navy: '#a9dfff',
    navy800: '#8ed4ff',
    navy700: '#6ec6ff',
    navy600: '#d4f0ff',
    baazex: '#5eb8f5',
    baazex600: '#3aa6ef',
    bright: '#7ed0ff',
    accent: '#1468b8',
    ink: '#0a1f44',
    muted: '#5a7194',
    canvas: '#f5f9ff',
    line: '#c9daf2',
    onButton: '#0a1f44',
    glow: '94 184 245',
  },
} as const

export type Brand = typeof BRAND
